export const PATH = {
    AUTH_TOKEN_API:'/easypay/token',
    AUTHENTICATION_API: '/api/authorization/login',
    FETCH_USERINFORMATION: '/api/AppUser/Detail',
    FETCH_ATTENDANCE_DETAIL: '/api/Dashboard/Attendance/Detail/{employeeID}/{date}',
    FETCH_VISITOR_DETAIL: '/api/Visitor/VisitorStatus/?Date={date}',
    CHANGE_PASSWORD: '/api/AppUser/ChangePassword',
    FETCH_LEAVE_BALANCE: '/api/Dashboard/Attendance/LeaveBalance/{1}',
    FETCH_LEAVE_HOLIDAY: '/api/Dashboard/Attendance/Holiday/{1}/{2}',
    FETCH_REQUEST_LIST: '/api/Employee/RequestList',
    POST_LEAVE_REQUEST: '/api/Attendance/Leave/RequestByEmployee',
    REQUEST_WORKFLOW_DETAIL: '/api/Employee/WorkFlow/ApproverDetail/{workflowid}',
    FETCH_APPROVE_HISTORY: '/api/Approver/RequestList',
    APPROVE_REQUEST: '/api/Approver/ApproveReqest',
    FETCH_REQUEST_FLOW_DETAIL: '/api/Employee/FlowDetail/{transactionID}',
    CANCEL_REQUEST:'/api/Employee/CancelUndoRequest/{1}/{2}',
    MARK_ATTENDENCE:'/api/Punch/Attendance/RequestByEmployee',
    UPLOAD_PUNCH:'/api/Punch/Attendance/UploadPunchImage',
    AUTHORIZE_MENU: '/api/AppUser/AuthorizedMenu',
    POST_GATE_PASS_REQUEST: '/api/GatePass/RequestByEmployee',
    FETCH_ATTENDANCE_DETAIL_FROM_TO: '/api/Dashboard/Attendance/Detail/{employeeID}/{fromdate}/{todate}',
    GET_PAYSLIP_HTML:'/api/Payroll/SalarySlip',
    FETCH_ALL_VISITOR_REQUEST:'/api/Visitor/GetList?',
    SEARCH_VISITOR_REQUEST:'/api/Visitor/Search?',
    SUBMIT_VISITOR_REQUEST:'/api/Visitor/Request',
    APPROVE_REJECT_VISITOR_REQUEST:'/api/Visitor/ApproveRequest?',
    FETCH_NEWS_ANNOUNCEMENTS: '/api/Employee/NewsAnnouncementDashboard/{fromdate}/{todate}',
    SUBMIT_PUNCH_REGULARIZATION_REQUEST: '/api/Punch/Regularization/RequestByEmployee',
    Teams_Details:'/api/EmployeeManage/GetTeamAttendance?'
  }
